name: Create tag
run-name: Create tag for ${{ github.ref_name }}
permissions: write-all

on:
  push:
    tags:
      - "@agusmgarcia/react-essentials-commands@v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Get version from tag
        id: get-version-from-tag
        uses: frabert/replace-string-action@v2
        with:
          pattern: ^(?:(.+?)@)?v(\d+)\.(\d+)\.(\d+)$
          replace-with: $2.$3.$4
          string: ${{ github.ref_name }}

      - name: Create tag
        run: |
          TAG_NAME=v${{ steps.get-version-from-tag.outputs.replaced }}
          git tag $TAG_NAME
          git push origin $TAG_NAME
